# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'WirelessLoop' do
use_frameworks!
pod 'SnapKit'
pod 'SDWebImage'
end

